# Generated by Django 4.2 on 2023-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Name', models.CharField(max_length=50)),
                ('Skill_priority', models.CharField(choices=[('1', 'LOW'), ('2', 'MEDIUM'), ('3', 'HIGH')], max_length=10)),
                ('Skill_Image', models.ImageField(upload_to='media/skill_image')),
            ],
        ),
    ]
