# Generated by Django 4.2 on 2023-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='Skill_Image',
            field=models.ImageField(upload_to='skill_image'),
        ),
    ]
